name: Compile Assets on develop and merge to staging

on:
  push:
    branches:
      - develop

jobs:
  compile-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: staging
          github_token: ${{ github.token }}
          
      - name: Checkout Staging
        uses: actions/checkout@v3
        with:
          branch: staging

      - name: Install dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build
        
      - name: Commit assets
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add build assets
