name: Compile Assets on develop and merge to staging

on:
  push:
    branches:
      - develop

jobs:
  build_and_merge:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build
        
      - name: Commit assets to staging
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add build assets
          branch: staging
