name: Compile Assets on develop and merge to staging

on:
  push:
    branches:
      - develop

jobs:
  build_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build

      - name: Checkout staging
        uses: actions/checkout@master
        with:
          ref: 'staging'

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Add build assets"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
